import Navigation from "./components/Navigation";
import "./globals.css";
import { CounterContextProvider } from "./store/context-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-start ">
          <Navigation />
          <div className="m-[50px]">
            <CounterContextProvider>{children}</CounterContextProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
